Added Protocol-Capability
paypal/SeLion pull request #382
Opened 2018-10-10 08:25 UTC by marvindoering

Updated DriverFactoryHelper to support "HTTPS" via configurable parameter "SELENIUM_PROTOCOL".

I ran into an issue while trying to connect to a remote device cloud which only supports "HTTPS". Therefore I added a new capability "SELENIUM_PROTOCOL" to change the protocol from "HTTP" to "HTTPS" if needed. Standard for this capability is set to "HTTP". 

- [X ] By placing an `X` in the preceding checkbox, I verify that I am a PayPal employee or
I have signed the [Contributor License Agreement](https://github.com/paypal/SeLion#contributing)

---

2018-10-10 18:55 UTC, mach6 commented
@marvindoering thanks for the contribution. Is there a test tat can be added for the proposed change?

2018-10-11 13:13 UTC, marvindoering commented
I did add some tests. Unfortunately does the build fail. I did test the same maven script that runs on travis-ci locally on my system and it seems to fail aswell. But if I ran the Chrome-Suite.xml in Eclipse the test do not fail. Did I configure something wrong?

2018-10-12 07:25 UTC, marvindoering commented
@mach6 Fixed the build by bumping the chromedriver-version to 2.42 to support the latest stable chrome version. Now both required tests are green. Ready for merge :smiley:

2018-10-16 23:29 UTC, mach6 requested changes
Looks good.. Will you please make the minor changes? Thanks!

2018-10-16 23:29 UTC, mach6 commented on client/src/test/java/com/paypal/selion/configuration/ProtocolConfigTest.java
> +|  Copyright (C) 2014 PayPal                                                                                          |
This should be the year(s) the file was created and/or modified 

So it should be 2018. :)

2018-10-16 23:29 UTC, mach6 commented on client/src/test/java/com/paypal/selion/configuration/ProtocolConfigTest.java
> +    public void testInitProtocalConfigNegativ() {
Can you change this to `Negative`? :)

2018-10-16 23:29 UTC, mach6 commented on client/src/test/java/com/paypal/selion/configuration/ProtocolConfigTest.java
> +    			"Negativ-TC: PROTOCOL should match the suite-file. (https) is set in suite file -> not (http)");
Here too.. `Negativ` vs `Negative`

2018-10-16 23:29 UTC, mach6 commented on server/src/main/resources/config/download.json
> +      "checksum": "28d91b31311146250e7ef1afbcd6d026"
👍

2018-10-17 06:57 UTC, marvindoering commented
@mach6 I did the required changes to the sourcecode. Hopefully now everything is good to be merged.

2018-10-17 19:42 UTC, mach6 approved these changes
Thanks @marvindoering

2018-10-17 19:43 UTC, merged